### ISSUE TITLE
KMS encrypt of private keys causes unnecessary CloudFormation replacements

### ISSUE THREAD

**Issue by pieterlange** [coreos/kube-aws#107]
Each KMS encrypt operation results in different ciphertext, causing updates of the userdata section inside of the launchconfiguration. This results in complete cluster rollovers on no-op's/changes to only one cluster component (eg instance type)

Haven't checked what happens with nodepools yet.

Some solutions to this issue:
  * put encrypted blobs in an S3 bucket
  * cache encrypted blobs and only update userdata on actual updates

I like the S3 bucket idea more if only because we don't need to keep local `kube-aws` state but would like some input from the community.

**Comment by mumoshu** [comment]
Hey @pieterlange, thanks for reporting this 👍

I believe I'm observing the same cluster rollover issue(to be extra clear, for only workers and controllers because they're updatable) when I run `kube-aws update` without modifying `cluster.yaml`.

I have been lacking a chance to investigate this further so I'm not yet quite sure why this is happening.

Could you mind telling me why KMS produces different ciphertext for each encryption?
Does it embed something changes for each encryption to ciphertext, maybe something like an one-time data key=pub key generated to encrypt data?

**Comment by pieterlange** [comment]
This is simply the nature of KMS. You can try it for yourself using `aws kms encrypt --key-id "arn:aws:kms:region:yourkey" --plaintext foobar` and see it produce 2 different ciphertexts for the same plaintext.

**Comment by mumoshu** [comment]
@pieterlange Thanks 👍 

So, I'd like to go with:

> cache encrypted blobs and only update userdata on actual updates

for the mean time because it has very small delta from current implementation to fix the exact issue.

In the future, I'm personally considering whether if it would be nice or not to add something like `--s3-state-uri s3://mybucket/kube-aws-states` to kube-aws so that we can persist the whole state including:

* cluster.yaml
* user-data/*
* stack-template.json
* credentials/*
* (new!) encrypted credentials

to S3.

It will free us from persisting kube-aws generated assets to somewhere else than a local disk by our own.
Btw, if I recall correctly, kops does a similar thing to persist states to S3.

Does:

> put encrypted blobs in an S3 bucket

seem to be covered within my idea?

**Comment by pieterlange** [comment]
Yes, but i don't think we should put the bare credentials in S3. Also: do we want to check if local state differs from state in S3? Or simply overwrite it?

I keep the kube-aws directories in a git repo (including the kube-aws binary, excluding credentials/*) for collaboration with other ops.

**Comment by cmcconnell1** [comment]
Thanks (for creating and maintaining kube-aws and) for addressing these security/cert issues.  I've been wondering what the best method would be to handle the credentials data dir for our distributed team (since we don't check that dir into git, etc.).  (Sadly, I've been using "scp -r" to manage them on EC2 bastion servers.)  It would be great if we could get the data encrypted and onto S3!

**Comment by mumoshu** [comment]
@pieterlange Certainly. How about only persisting `credentials/*.enc` which are encrypted versions of original credentials so that a whole state would look like:

* cluster.yaml
* user-data/*
* stack-template.json
* credentials/*.enc

I would even consider automatically removing plain `credentials/*.pem`s entirely after successful encryption, regardless of whether they're finally persisted locally or remotely.

For the local/remote state preference, I guess it'll be almost like overwriting when `--s3-state-uri` is provided/enabled.
In my ideal world, specifying `--s3-state-uri` would denote that an user wants to store the whole state not locally but remotely in S3. Therefore `kube-aws` should download the state from S3 and may put it in a working directory(somewhere like `/tmp/kube-aws/cache/states/<cluster-name>` for temporary use.

**Comment by mumoshu** [comment]
@cmcconnell1 Thanks as always for trying kube-aws 😄 

It is really up to users currently. However, if you'd like to build a serious production system with kube-aws, I'd personally recommend you to write, at least, a wrapper script for kube-aws which streamlines the following tasks:

* download the whole encrypted kube-aws assets from S3 and put them to a working directory
* decrypt them
* automatically or manually manipulate cluster.yaml, stack-template.json, userdata/cloud-config-*, etc.
* run actual kube-aws commands like up, update, destroy, etc.
* re-encrypt all the assets
* upload the latest, encrypted assets to S3 and remove the working directory

Encryption/decryption could be applied to a subset of kube-aws assets but it should contain `credentials/*.pem` at minimum.

Btw, I assume this kind of work(securely storing/transfering states of something) should be done regardless of we use kube-aws or not.
We should encrypt all the secret informations e.g. credentials regardless of using kube-aws or not, right?
So, I'd rather like such wrapper scripts to be implemented outside of kube-aws because security requirements among projects and/or organizations.
But I'm ok for it to be implemented in kube-aws itself or under the `contrib/` of kube-aws, like what I've written in https://github.com/coreos/kube-aws/issues/107#issuecomment-264382804, if there're certain needs.

**Comment by mumoshu** [comment]
Let's discuss about the remote state persistence in #123, which is branched off from this.

**Comment by mumoshu** [comment]
I'm going to fix this in 0.9.2-rc.4
