### ISSUE TITLE
Default route 0.0.0.0/0 needs to be added to subnet generated by kube-aws before it can speak to internet.

### ISSUE THREAD

**Issue by jessesanford** [coreos/kube-aws#121]
The security groups that are generated leave port 22 open to 0.0.0.0/0 however there is no default route in the subnet that is generated. I believe that for consistency it should either add the default route or if security/minimum exposure is desired we should remove that security group ingress rule to allow ssh traffic from everywhere.

**Comment by c-knowles** [comment]
I thought this was done via [`RouteToInternet`](https://github.com/coreos/kube-aws/blob/master/config/templates/stack-template.json#L1052), although I've only just started using the very latest master version. Which version and combination of cluster.yaml settings are you using?

**Comment by mumoshu** [comment]
Thanks for trying kube-aws @jessesanford!
That route should be automatically created via `RouteToInternet` as @c-knowles mentioned.
Actually, I've been verifying kube-aws-created clusters are accessible via SSH over the internet each time in E2E testing.
Would you mind double-checking the situation?

**Comment by jessesanford** [comment]
Ok I can re-create this. 
See below for my cluster.yml
```
kube-aws version v0.9.2-rc.2
```

To start create a new empty vpc. Don't change any settings including incorrectly leaving internet gateway detached from the vpc. Then try

```
kube-aws up --s3-uri s3://stn-kubernetes/kubernetes
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [IAMInstanceProfileWorker, SecurityGroupEtcdPeerIngress, ElbAPIServer, IAMInstanceProfileController, IAMInstanceProfileEtcd].

Printing the most recent failed stack events:
CREATE_FAILED AWS::CloudFormation::Stack kubernetes The following resource(s) failed to create: [IAMInstanceProfileWorker, SecurityGroupEtcdPeerIngress, ElbAPIServer, IAMInstanceProfileController, IAMInstanceProfileEtcd].
CREATE_FAILED AWS::ElasticLoadBalancing::LoadBalancer ElbAPIServer VPC vpc-3b60b75c has no internet gateway
```

Then correctly add the internet gateway and try again:

```
kube-aws up --s3-uri s3://stn-kubernetes/kubernetes

Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: error validating existing VPC: instance cidr (10.0.0.0/24) conflicts with existing subnet cidr=10.0.0.0/24
```

Now delete the broken cluster:

```
 kube-aws destroy 
CloudFormation stack is being destroyed. This will take several minutes
```

And recreate 1 last time:

```
kube-aws up --s3-uri s3://stn-kubernetes/kubernetes [2.3.1]
Creating AWS resources. This should take around 5 minutes.
Success! Your AWS resources have been created:
Cluster Name:           kubernetes
Controller DNS Name:    kubernete-ElbAPISe-N46PMAP5CYPB-1328932374.us-west-2.elb.amazonaws.com

The containers that power your cluster are now being downloaded.

You should be able to access the Kubernetes API once the containers finish downloading.
```

I end up with a subnet without a route to the internet gateway:

<img width="860" alt="kube-aws subnet without default route" src="https://cloud.githubusercontent.com/assets/108698/20912236/13a9fc66-bb3c-11e6-85de-9ee53181117f.png">

**Comment by mumoshu** [comment]
@jessesanford Thanks for the info!

Odd.
Do you know how was the subnet `subnet-44404b32` created?
Is it managed by the cloudformation stack created via kube-aws?
If it was created by kube-aws, it must be named like `<cluster-name>-Subnet0`, which is not the case.

**Comment by mumoshu** [comment]
Ah, are you just referring to an existing subnet?
If that's the case, could you look for subnets named like `<cluster-name>-Subnet0`?
These are subnets used to deploy nodes.
kube-aws don't rely on/or modify existing subnets.

**Comment by mumoshu** [comment]
@jessesanford Any chance you could take a look into my comments since then?

**Comment by jessesanford** [comment]
Sorry. It is not an existing subnet. The subnet is created by the kube-aws
cf template. It is suffixed by "-Subnet0"

On Dec 9, 2016 12:07 PM, "KUOKA Yusuke" <notifications@github.com> wrote:

@jessesanford <https://github.com/jessesanford> Any chance you could take a
look into my comments since then?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/coreos/kube-aws/issues/121#issuecomment-266067030>, or mute
the thread

**Comment by mumoshu** [comment]
@jessesanford Thanks for the info!

It seems to be now clear that I had been mis-understanding your situation.

So:

* Your cluster is being deployed to an existing VPC specified by `vpcId` in cluster.yaml
* `routeTableId` is missing in cluster.yaml
* You've manually removed the internet gateway from the VPC and then added a new one to it.
* But you had not updated route table manually to route `0.0.0.0/0` to the newly added internet gateway

right?

If thats the case, I suggest you to:

* Manually update existing route table to route `0.0.0.0/0` to the internet gateway
* Provide the route table's id to `routeTableId` in your cluster.yaml

so that kube-aws could create appropriate `RouteTableSubnetAssociation`s.

This is a bit cumbersome but the point is that, if you've specified `vpcId` in cluster.yaml, kube-aws creates neither a route table nor a route table subnet association for you (ref https://github.com/coreos/kube-aws/blob/master/config/templates/stack-template.json#L1120)

To be extra clear, **If you've specified `vpcId`, it is now your responsibility to provide a properly configured route table's Id to `routeTableId` in cluster.yaml**.
There may be some space for improvement on kube-aws side(e.g. documentation, validation), it is so for the time being.

**Comment by mumoshu** [comment]
Anyways, I've written about this in our documentation at https://github.com/coreos/kube-aws/blob/master/Documentation/kubernetes-on-aws-prerequisites.md#deploying-to-an-existing-vpc
I'm closing this for now but please feel free to reopen if your case isn't covered by the doc!
