### ISSUE TITLE
Feature: DNS horizontal autoscaling

### ISSUE THREAD

**Issue by mumoshu** [coreos/kube-aws#172]
The upstream Kubernetes seems to have adapted to utilize cluster-proportional-autoscaler to horizontally auto-scale kube-dns pods since 1.5.
Would it be nice to support it out of box in kube-aws, too?

Relevant upstream issue: https://github.com/kubernetes/kubernetes/pull/33239

Setting min replicas to at least 2 would also result in fixing #111

**Comment by c-knowles** [comment]
We may need the rescheduler work too if the min size is 2 and worker count is 2? Since a node dying in that scenario means both DNS pods would be scheduled on the same node assuming there was enough resource to schedule; then when a new second joins the pod is not rescheduled to it without the rescheduler I believe.

**Comment by mumoshu** [comment]
That's a good point 👍
I have not yet tried that myself, but yes, I believe rescheduler is required to treat such case.

**Comment by mumoshu** [comment]
Recommended reading: [Using DNS Horizontal Autoscaling feature in Kubernetes](https://gist.github.com/MrHohn/1198bccc2adbd8cf3b066ab37ccd8355)
