### ISSUE TITLE
Documentation issue at kubernetes-on-aws-render.md

### ISSUE THREAD

**Issue by reiinakano** [coreos/kube-aws#203]
The documentation at https://github.com/coreos/kube-aws/blob/master/Documentation/kubernetes-on-aws-render.md contains a broken link. This one -> [enable the cluster logging add-on](https://github.com/coreos/kube-aws/blob/master/Documentation/kubelet-wrapper.md#use-the-cluster-logging-add-on). I really want to know how to add the cluster logging functionality with kube-aws.

Edit:
Upon closer inspection, these other links are broken too

allow pods to mount RDB or iSCSI volumes
allowing access to insecure container registries
use host DNS configuration instead of a public DNS server

**Comment by mumoshu** [comment]
@reiinakano Thanks for trying kube-aws and sorry for inconvenience here :bow:

[The documentation had been describing how to expose k8s log files under `/var/log` to be consumed by a log forwarder like fluentd](https://github.com/coreos/coreos-kubernetes/commit/d234992bef67e80378018abb172b41e536d06749). However the doc has been removed because `/var/log` is exposed by default in coreos and kubelet-wrapper as of today.

Also, unfortunately, configuration of a log forwarder like fluentd is currently out of scope of kube-aws. Therefore I guess looking for docs in kube-aws won't solve your actual problem but rather searching for it in the upstream doc would do.

Although I'm afraid I can't help you as a maintainer of kube-aws, I think I can help you personally with https://github.com/mumoshu/kube-fluentd. It is my personal project to launch fluentd log forwarders over you cluster to make logs available via [GCP Stackdriver Logging](https://cloud.google.com/logging/). If you'd like logs aggregated to something other than Stackdriver Logging, I'd recommend you to take a look into [the list of fluentd output plugins](http://docs.fluentd.org/articles/output-plugin-overview#) and swap the output plugin.

FYI, running fluentd for k8s in right way is slightly cumbersome:
* https://github.com/kubernetes/kubernetes/issues/32762
* https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/87

I hope using my kube-fluentd as the foundation of your own cluster logging would alleviate the cumbersomeness.

// BTW, to be clear, the cumbersomeness is not originating from fluentd but rather distributed logging itself. fluentd does the job very well if it was properly configured.

---

For links other than cluster logging, thanks for the feedback! It seems we've missed to revisit/fix those when we had moved our git repo from coreos/coreos-kubernetes to coreos/kube-aws(this repo).

Looking at the url of the link reveals that `kubelet-wrapper.md` is what we're looking for and it can still be located at:
* https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html
* https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md

You can I'll fix the links with the above but would greatly appreciate your pull request.

**Comment by reiinakano** [comment]
Awesome. Thanks for clarifying that. I'll check out kube-fluentd.

Btw, this link -> [allowing access to insecure container registries](https://coreos.com/os/docs/latest/registry-authentication.html#using-a-registry-without-ssl-configured) is still broken. Couldn't find where it's been moved.

**Comment by mumoshu** [comment]
It seems like the doc had been removed (hence 404) and is now coming back via https://github.com/coreos/docs/pull/970

**Comment by ElijahCaine** [comment]
That doc ( coreos/docs#970 ) was just merged back in. Soon it'll get picked up and added to the website again.

**Comment by mumoshu** [comment]
@ElijahCaine Thanks for the the PR and info 👍

**Comment by reiinakano** [comment]
Closing this issue as the link is no longer a 404
