### ISSUE TITLE
Userdata limit of 16KB is almost reached 

### ISSUE THREAD

**Issue by redbaron** [coreos/kube-aws#252]
LaunchController userdata size is almost 16KB and starts to fail if few modifications added. We need to find another way topass userdata, such as s3 bucket.

**Comment by danielfm** [comment]
I just bumped into this when trying to move my customizations from earlier versions of kube-aws to the new ones. The error message when that happens is not pretty as well:

```
$ ~/kube-aws up --s3-uri ...
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [InstanceEtcd0, LaunchConfigurationController].

Printing the most recent failed stack events:
CREATE_FAILED AWS::CloudFormation::Stack kube-aws-test The following resource(s) failed to create: [InstanceEtcd0, LaunchConfigurationController].
CREATE_FAILED AWS::AutoScaling::LaunchConfiguration LaunchConfigurationController 1 validation error detected: Value 'H4sIAAAJbogA/+z9eZeq2JYoiv+fn4JfVN6b5/zcBiDYxXlxRwEi0ggI2FbW2INm0UgrnWJWfvc37CLU0IjYTZ66r6rMMXaGMNecc821Zrsa/8UM4sKqm3Fke84vZpyCOHv6BYKKxNJzsPsLglJgxHFez/JUz4FTPUEPsW0//AJBdqBHEQgOUF6Ug9TWTfAE/ZqkXqnn4KuXlPj+JchN6yuIrCT2ojx7gtw8T7InGPaSOorUd//hj5leB3qW19FHMw6TIgePe5SRHjw1sHb3FY+p214AniAY5CbsFwZII5CDDM6yADb1xwSEZ7Agze9D70DqZuCBKL9s5oPqU63qPqj2LXcii7w8e/plj6QORXoInqAM5HV9ndVBVHppHIU7QhlIS88EezgIApFu7AjlaXF6ZMZhqEfWE5TlepofH6ZFlHvhNWCUgyh/gv7j+ACC/m0cefm/v3ztgcxMvST34uhZBTlETFXojBeo1FNvRz+DvOjQ1ytuXzARdg7S5wjk6zj163EUeBF4zPXUAfkvr9TVQ99eGdCqBDzHEcjc+BWXAkLdi/YY6Y2XP591CYLoDTDVXcflFDzDhhfBeVyY7vvcvTR6hoss3bdK/XwnNOj3FyAIqteLwrPqu6GtZ3oJnuFST+G0iODDzIdNO6p7kZc/7uCumpZxUITg2YqyL74XWc9unOVfsrhITfC8Zy4FWRyUjztd+pIC3ZKioNr3DarXw7jYifsVxUF0bxrepqmvMxCVd8heyeSVtK0H2RvaR1Tn5K8QXLEQgXxP8+pxnhbZfvpndTuNw/peoy9gVoVePXrxSbT6OjMD7ynUsxykUL0OnWQN1cuLdgf8KXC8OIJejMJNkIMYIEEvItOl9jasSPXdbKfiKE/jIADpjYZZrps+tNPqvXLmIMsv1daKTR+kV5pqpXFS96KTip/Do0j90OQg6/1InlG9oafQW12FXrSs1NN64BlHnI97nBdgUz3Ks9tg
```

Calico seems to the "heaviest" extension in that regard, so I had to disable it in order to put my own customizations there.

**Comment by redbaron** [comment]
I am preparing PR where user-data files are uploaded to same bucket where CF template is uploaded. Then userdata for hosts will be something like:

```
#!/bin/sh
set -ue

REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')

/usr/bin/rkt run \
   --net=host \
   --volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=dns,target=/etc/resolv.conf  \
   --volume=awsenv,kind=host,source=/var/run/coreos,readOnly=false --mount volume=awsenv,target=/var/run/coreos \
   --trust-keys-from-https \
   quay.io/coreos/awscli:master  -- aws s3 --region $REGION  cp s3://{{ .CFBucketPath }}/controller-userdata /var/run/coreos/

exec /usr/bin/coreos-cloudinit --from-file /var/run/coreos/controller-userdata
```

**Comment by whereisaaron** [comment]
@redbaron are these S3 buckets intended to be all kube-aws launches, or per cluster, or per node-pool?

E.g. I notice the `kube-aws up` and `kube-aws node-pools up` seem to use the same file name for the `stack.json` file. I wondered if that means if you launch two node-pools at once you could inadvertently cross-pollinate the stack.json unless you use different buckets?

Likewise your example here for userdata is using a generic (not prefixed) filename. For controllers this might not matter, but for node-pool workers the data could be different, and launching two node pools at once could clash if the same bucket is used.

Do you think these S3 launch files should be prefixed with the cluster/node-pool names (or folder prefix maybe)? Or should users ensure a different bucket is used for each controller/node-pool launch in every cluster?

**Comment by mumoshu** [comment]
// I'm still scratching my head about it.

Hi @crawford, we'll probably migrate from coreos-cloudinit to ignition sooner or later and would you mind telling me if ignition could be enhanced to support:

1. reading files from a secured(!=not accessible from anonymous users) s3 bucket probably using `contents.source` or
2. reading additional configs from a secured s3 bucket probably using `config.append[].source`?

I'm asking this after reading:
* https://groups.google.com/forum/#!topic/coreos-dev/PPInhPPqDsw
* https://github.com/coreos/ignition/pull/183

--

Our problem is that `cloud-config`s for kube-aws are reaching to the limit of 16KB in size and the `cloud-config`s "may" contain sensitive data.
AFAIK the limit is coming from AWS so it would also affects us after we've migrated to ignition.
`source` in ignition config as of today doesn't seem to support authentication therefore I'm assuming we need to enhance it to support authentication or discover another work-around(e.g. a http proxy between s3 and ignition? 😛)

As kube-aws relying on coreos-cloudinit, we'll probably go ahead with the @redbaron's method summarized in https://github.com/coreos/kube-aws/issues/252#issuecomment-272850696 in short term but after the future transition to ignition, I began to believe we don't have a solution to work-around the limit.

**Comment by crawford** [comment]
Hey @mumoshu, I'm good. How are you? :smiley:

> 1. reading files from a secured(!=not accessible from anonymous users) s3 bucket probably using contents.source or
> 2. reading additional configs from a secured s3 bucket probably using `config.append[].source`?

I've been thinking about this a bit recently. I'm not sure just yet how I want to encode that information in the config and if it should even be there at all. In the mean time, you can use [S3 Signed URLs](http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html) to allow a specific machine access to a particular resource for a set period of time.

**Comment by mumoshu** [comment]
@crawford Fine but been busy these days 😄 

> I've been thinking about this a bit recently. I'm not sure just yet how I want to encode that information in the config and if it should even be there at all. In the mean time, you can use [S3 Signed URLs](http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html) to allow a specific machine access to a particular resource for a set period of time.

Thanks 👍 
It sounds like a good idea but would you mind clarifying a bit?

Is there any way to add a "hook" which starts before ignition, so that we can dynamically create signed urls and then pass those to ignition or even dynamically create an ignition config?

I'm personally thinking that creating signed urls before the cluster creation wouldn't be a solution because then we'd certainly need to set very long expiration period for signed urls, which would be a security risk.

What we're going to have (thanks to @redbaron) for providing coreos-cloudinit a cloud-config read from S3 is something like:

```bash
#!/bin/bash",
# userdata hash: {{ .UserDataWorker | sha1 }},
. /etc/environment
export COREOS_PRIVATE_IPV4 COREOS_PRIVATE_IPV6 COREOS_PUBLIC_IPV4 COREOS_PUBLIC_IPV6
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')
USERDATA_FILE=userdata-worker
/usr/bin/rkt run \
   --net=host \
   --volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=dns,target=/etc/resolv.conf  \
   --volume=awsenv,kind=host,source=/var/run/coreos,readOnly=false --mount volume=awsenv,target=/var/run/coreos \
   --trust-keys-from-https \
   {{.AWSCliImageRepo}}:{{.AWSCliTag}} -- aws s3 --region $REGION  cp {{ .S3URI }}/{{ .StackName }}/$USERDATA_FILE /var/run/coreos/
exec /usr/bin/coreos-cloudinit --from-file /var/run/coreos/$USERDATA_FILE
```

Is there any way to hook into ignition like this?

**Comment by crawford** [comment]
@mumoshu me too. Very very busy.

> Is there any way to add a "hook" which starts before ignition, so that we can dynamically create signed urls and then pass those to ignition or even dynamically create an ignition config?

Glad you asked. This is actually how Ignition is intended to be used. We've been working on [`ct`](https://github.com/coreos/container-linux-config-transpiler), which is a tool for generating Ignition configs from a human-friendly version. It is extremely simple right now, but we have plans for providing a whole lot of sugar to make common operations very easy.

> I'm personally thinking that creating signed urls before the cluster creation wouldn't be a solution because then we'd certainly need to set very long expiration period for signed urls, which would be a security risk.

You could add a service to your config which purges the remote Ignition config before accepting work on the machine. That way, if a user downloaded the userdata, they would get a URL to the actual config that just 404'd.

> What we're going to have (thanks to @redbaron) for providing coreos-cloudinit a cloud-config read from S3 is something like:

How does authentication work in this case? Are the secret and key exported before that script is run or are you using IAM roles? Instead of signed URLs, another option would be to use IAM roles to allow that one instance to access it's config. That might be easier to configure.

**Comment by mumoshu** [comment]
@crawford Thanks for your reply!

> This is actually how Ignition is intended to be used. We've been working on ct, which is a tool for generating Ignition configs from a human-friendly version.

ct definitely seems to be useful! In the future, kube-aws will probably generate a ct `config/golang text template` for customization of node bootstrap process, instead of the current one; `cloud-config/golang text template`.

> You could add a service to your config which purges the remote Ignition config before accepting work on the machine. That way, if a user downloaded the userdata, they would get a URL to the actual config that just 404'd.

Thanks but how could you do that in an autoscaling environment?
Purging the remote ignition config in the first node would result in other nodes to be unable to find the config.

> How does authentication work in this case?

We're relying on IAM roles assigned to nodes via instance profiles.
Could we use an iam role to obtain ignition configs and then feed ignition?

**Comment by mumoshu** [comment]
Closing this as the original issue is resolved thanks to @redbaron.

@crawford Sorry for bothering you but I'm still interested on how we can avoid this issue after we've migrated to ignition and ct!

**Comment by mumoshu** [comment]
https://github.com/coreos/ignition/pull/382 adds ignition an ability to write s3 objects as local files. Using it in kube-aws allows us to reduce overall size of the remote(s3) parts of cloud-config-(worker|controller|etcd). In other words, it would make the userdata splitting(into local and remote/s3 parts) not necessary.

cc @redbaron
