### ISSUE TITLE
Can't destroy node pools in 0.9.3-rc.5

### ISSUE THREAD

**Issue by numair** [coreos/kube-aws#276]
Now that I can create the node pools in the example, this is what happens when I try to destroy them (as per https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-destroy.html):

```
Machine:k8s-cluster user$ kube-aws node-pools destroy 
Error: Error parsing node pool config: open node-pools//cluster.yaml: no such file or directory
```

I'm doing this in the root of the folder containing all of the assets, as seen here:

```
Machine:k8s-cluster user$ ls
cluster.yaml		kubeconfig		stack-template.json
credentials		node-pools		userdata
```

Here's the relevant version info:

```
kube-aws version v0.9.3-rc.5
```

Let me know if I'm doing something wrong!

**Comment by neoandroid** [comment]
Currently the command needs the option `--node-pool-name` to do something. So the right command would be:
`$ kube-aws node-pools destroy --node-pool-name foo`

If the command should support the destruction of all node pools created when there is none specified as the documentation suggest is something the source code does not do so we should fix the source code or the documentation.
IMHO I would say that since there is no confirmation message when you use the `destroy` command such a destructive operation for not specifying additional required parameters by mistake could be too dangerous. I would add a `--all` flag if we want to support deletion of all node-pools and fix the documentation accordingly.

**Comment by numair** [comment]
@neoandroid Thanks, this was super-helpful.  Hope the maintainers get a chance to update the documentation so others don't get tripped up.

**Comment by mumoshu** [comment]
@numair @neoandroid Thanks for your info!
It is fixed in master.
https://github.com/coreos/kube-aws/commit/713f18b045fad9bf03c8a120791248c4eae064fe
