### ISSUE TITLE
DNS names in TLS certificate

### ISSUE THREAD

**Issue by RaphaelHerd** [coreos/kube-aws#285]
Hey guys,

is it possible to make the DNS names of the self signed certificates more dynamic. Right now you're creating the certificates based on

DNSNames: []string{
                        "kubernetes",
                        "kubernetes.default",
                        "kubernetes.default.svc",
                        "kubernetes.default.svc.cluster.local",
                        c.ExternalDNSName,

that DNS names in the tls_config.go. 

Is it possible to make that more flexible so that we are able to add more custom DNS names by using the cluster.config file?

Thank you

**Comment by redbaron** [comment]
generate your own certs

**Comment by pieterlange** [comment]
I agree that any customization on this front is up to the user - you can generate your own PKI certs using tools like easy-rsa, xca or plain old openssl for your specific needs.

**Comment by whereisaaron** [comment]
@RaphaelHerd here is a starter for a script you can use to generate your own certs for `kube-aws`
https://github.com/whereisaaron/coreos-kubernetes-generate-certs

They are a little out of date, because they don't generate the `etcd` certificate `kube-aws` needs now, but you should be able to update them (and send me PR please 😄 ).

**Comment by RaphaelHerd** [comment]
Sry for my late response. I changes the default DNS names that are denoted in the tls_config.go file. For my test case I don't need any official CA.

So you can close the issue

Thx for help
