### ISSUE TITLE
Question: v0.9.3 Release

### ISSUE THREAD

**Issue by yawboateng** [coreos/kube-aws#288]
Hello All,
apologies if this is not the right place to post this but is there a place where I can get information on when v0.9.3 binaries will be ready?

**Comment by cmcconnell1** [comment]
@yawboateng  AFAIK, until CoreOS signs the packages and the binaries become available, you have to build from (master) branch.  Only takes a minute though
see https://github.com/coreos/kube-aws#build

**Comment by drywheat** [comment]
I honestly wonder how long it will take CoreOS to sign those binaries.

1. This pre-release came out 22 days ago.
2. Even more surprising, **v0.9.2** was released on Dec 15, 2016 and it is still unsigned.

**Comment by pieterlange** [comment]
@philips could you appoint someone at CoreOS to take care of this? :)

**Comment by redbaron** [comment]
it doesn't look like coreos is interested in developing this product further

**Comment by yawboateng** [comment]
@mumoshu, any update on this?

**Comment by AlmogBaku** [comment]
@mumoshu @colhom ?

**Comment by mumoshu** [comment]
Hi all,

I've talked with @colhom and decided to drop the signing process (at least for now) so that we can deliver non-rc releases faster.

I'll build v0.9.3 myself and release it if necessary.
However, if you're not yet running a prod env with it, I'd rather appreciate it if you could use v0.9.4-rc.1 or greater and leave feedbacks if any, so that we can together accelerate development of kube-aws.
 Is anyone willing to use v0.9.3?

Also, I'm not yet sure the signing process is coming back in the future. Anyways, the fact is that neither I nor CoreOS folks have a "key" or a way to share the "key" to sign released binaries, in a sustainable way. Anyone is relying on it? Anyone is willing to provide me a "key" or anything else as an alternative? If no, I believe that the signing process is kept dropped.

**Comment by mumoshu** [comment]
Anyway, I've released v0.9.3.
