### ISSUE TITLE
colocate etcd on the masters

### ISSUE THREAD

**Issue by yawboateng** [coreos/kube-aws#298]
I was wondering if there is an optional setting to have etcd run on the master/controller nodes 

Reason: I have some none production environments that i want to keep as small as possible, and I feel am wasting resources using a separate master and etcd nodes. and it will be great to be able to pass in an option during deployment to either have etcd run on the master or use a dedicated node

**Comment by sasso** [comment]
I was wondering that too, how come that you decided to run a separate etcd cluster and not use existing machines. Also if I'm not mistaken Tectonic runs etcd on every controller/worker node. Also would it be HA and failure prone if you would run etcd on every node with combination of proxy nodes on workers?

**Comment by mumoshu** [comment]
Hi, thanks to you two for the feedbacks!
Excuse me if I'm repeating what you already know but first of all, running etcd proxy on every node doesn't contribute to HA of an etcd cluster at all.
Regardless of proxies, once majority of etcd nodes(2 for 3 nodes cluster and 3 for 5 nodes cluster and so on) goes down, your etcd cluster stops working.
Also note that you have to avoid having an odd number of etcd nodes for your cluster because then there's no way to avoid split-brain problems almost certainly you'd like to avoid in your production environment.
Now, what if you had etcd running on every node or even every controller node of your cluster?
Once the number of your nodes gets even via e.g. autoscaling, your cluster faces a potential split-brain.
That's why I recommend you to have - at least relative to worker and controller nodes - a fixed, odd number of nodes dedicated to etcd.
I don't know much about Tectonic but I've heard that it runs self-hosted etcd. It doesn't mean you run etcd on every node but probably "run odd number of etcd pods" among all the nodes.

**Comment by yawboateng** [comment]
Hi @mumoshu  thanks for the response, 
what would you recommend as the minimum instance size (m4.large, m3.medium etc) of an etcd node

**Comment by mumoshu** [comment]
Hi @yawboateng!
I recommend m4.large(which is the minimum one recommended by etcd/coreos team!) or larger for etcd nodes in a production environment.
I've written a general guidance previously in an another issue at https://github.com/coreos/kube-aws/issues/181#issuecomment-268705548

**Comment by mumoshu** [comment]
Closing this for now but please feel free to reopen if necessary.
Also please see #27 for planned improvements in the etcd management.
