### ISSUE TITLE
Avoid the 51200 bytes limitation errors of CloudFormation

### ISSUE THREAD

**Issue by mumoshu** [coreos/kube-aws#38]
With the current master 6255751f2a446882dadcd71ac4d88e921520c8ee, when creating a test cluster for E2e testing, I've finally hit the limitation error:

```
*your template body here* at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
```

**Comment by mumoshu** [comment]
Quick thought, but to not break the current usage and user experience of `kube-aws up`, I'm not specifically opposed to automatically putting a cloudformation template on S3 before creation in `kube-aws up`, at least for now.

Also, I believe that doing so is an AWS-official way to go beyond the limit.

We can also split CloudFormation templates into several parts, possibly into the etcd, the controller and the worker part. I'm not sure this can be done shortly though.

Anybody have any ideas, thoughts, etc?

**Comment by mumoshu** [comment]
ok it turns out that @pieterlange had already mentioned this way of avoiding the limitation on last friday 👍
https://github.com/coreos/kube-aws/issues/29#issuecomment-258302989

**Comment by mumoshu** [comment]
Writing randomly to organize my idea 😃 

Note that, even if we revert the last few commits to reduce template size, it will be an issue sooner or later.
Also, regardless of how we reduce "minimum" template size like that, users can always add their own customizations to `cloud-config-(worker|controller|etcd)`, `stack-template.json` or etc freely, which may or may not end up with the same limitation errors.

**Comment by pieterlange** [comment]
I agree that for the short term we shouldn't break UX and upload the template to S3. 

Mid to long term i think there's no way around having to kick off multiple cloudformation templates, especially once we start looking at node pools (https://github.com/coreos/coreos-kubernetes/issues/667).

Starting multiple templates also involves a lot more work tracking resource id's across templates. I'm currently splitting my kube deployments in VPC, etcd and kube-aws cloudformation components, utilizing [Outputs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) to glue them together.

**Comment by iwarp** [comment]
Nested stacks are also an option, however it does get more complicated passing id's between templates. 
I've had to use s3 every time i've used cloudformation.

**Comment by c-knowles** [comment]
The new [cross stack references](https://aws.amazon.com/about-aws/whats-new/2016/09/aws-cloudformation-introduces-yaml-template-support-and-cross-stack-references/) are probably going to be helpful to avoid keeping track of Outputs. Plus I think we should swap to the YAML version of the CloudFormation as it's more readable and since it can be significantly smaller it may actually delay having to tackle this issue fully.

**Comment by mumoshu** [comment]
Thanks everyone for your valuable feedbacks :bow:

To keep the ball rolling, I've submitted one possibly way of resolving this to #45

Do you like it or prefer:

* seperate templates
* separate templates + cross stack reference
* nested stack
* combination of the aboves

?

Any feedback is welcome 🙏

**Comment by mumoshu** [comment]
@iwarp @c-knowles May I ask you how do you usually decide which one to use, nested stacks or cross stack references?

I'll probably end up using one of those while building POC for https://github.com/coreos/kube-aws/issues/46 but not sure which one to go.

**Comment by c-knowles** [comment]
Since they're quite different patterns sometimes you'd have to use one or the other. For example, say I wanted to link a single RDS layer to two stacks, then I'd have to use the stack references (or Outputs doing it the old way).

I tend to avoid nested stacks because it requires the additional complexity of uploading to S3.

The main difference from the perspective of updates is that a stack that uses nested stacks will only receive updates that are within that nested stack on its own next update. Whereas cross stack references mean more of an immediate update since they are completely separate entities.

**Comment by Tarvinder91** [comment]
Adding my 2 cents for people following the issue, you shall store your template on s3 first and use the following option in the aws cmd line as a workaround for large templates -

--template-url https://s3-<region>.amazonaws.com/...../yourtemplate.json

url should be https link of the template.
