### ISSUE TITLE
Proposal: enable to attach user defined security groups for worker instances.

### ISSUE THREAD

**Issue by everpeace** [coreos/kube-aws#43]
Hi community,  thanks for sharing the great project.  I'm very happy if I could contribute this project would be better.

# Motivation 
I think restricting access to ec2 instances by security group is a common pattern.  For example, assume the situation that you  had some database instances and you wanted to restrict access to those db instances by some specific security group.  

# Proposal
In such situations, I believe that `kube-aws` could be more useful if `kube-aws` can attach user defined security groups to its worker nodes.

# Current possible workaround and its disadvantage
We can use the security group which `kube-aws` will generate for worker nodes, let this be `sg-w`.  For above example, that means, we can configure the security group which will be attached to db instances, let this be `sg-db`, so that `sg-db` allows ingress from `sg-w`.

Unfortunately,  in this case, this doesn't allow user to destroy the k8s cluster unless user modified `sg-db` because`sg-w` is referred from `sg-db` and `sg-w` is managed by `kube-aws`.   I believe that this is not preferred by many users because this solution introduces undesirable dependencies.

**Comment by pieterlange** [comment]
I fully agree and ran into this myself a few times. 

The feature itself will be easy to add if we all agree we should implement this using a "glue" security group which is manually managed. We've recently added a bunch of "external" dependencies that leave some management up to the cluster operator, so i think this is fine too.

**Comment by mumoshu** [comment]
I'm ok with the `glue` security group 👍

I believe that's considerably better than making inconvenience like "`kube-aws destroy` seems to failed somehow.. oh, I'd been forgetting about the nearly invisible dependency from sg-db to sg-w....".

(Full disclosure: @everpeace is my colleague

**Comment by mumoshu** [comment]
OK so I believe it is now easier than ever to support additional security group(s) assigned to worker nodes since the experimental node pools feature landed.

Both the `stack-template.json` template and the `nodepool/config.go` which is the foundation of the template are already aware of any number(actually up to EC2 limit) of security groups assigned to each worker node in a pool:

https://github.com/coreos/kube-aws/blob/master/nodepool/config/config.go#L214-L220
https://github.com/coreos/kube-aws/blob/master/nodepool/config/templates/stack-template.json#L1-L7

Anyone likes to contribute here? 😃
