### ISSUE TITLE
EBS volumes using old-generation standard magnetic disks for controller and etcd

### ISSUE THREAD

**Issue by seffenberg-naspers** [coreos/kube-aws#68]
This issue was already explained once in https://github.com/coreos/coreos-kubernetes/issues/554 and was fixed in https://github.com/coreos/coreos-kubernetes/pull/559 but is missing for controller now in the stack-template.

Also the etcd (maybe on purpose?!) cluster is even not considered to be configurable at all.

**Comment by mumoshu** [comment]
@seffenberg-naspers Good catch! Thanks for your feedback :bow:

etcd:
![image](https://cloud.githubusercontent.com/assets/22009/20410666/8aa9f336-ad61-11e6-80bc-845bd2eae937.png)

controller:
![image](https://cloud.githubusercontent.com/assets/22009/20410644/6aa4077a-ad61-11e6-8440-0729241de067.png)

worker:
![image](https://cloud.githubusercontent.com/assets/22009/20410652/7bd363b0-ad61-11e6-8418-2bc3d78fedd6.png)

It seems that we've been missing it since discrete etcd and HA control plane.

**Comment by seffenberg-naspers** [comment]
Thanks!
